env:
  LIBRARY: "build/libglnet.a"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      timeout-minutes: 2
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Configure CMake
      timeout-minutes: 2
      run: cmake -B build/ -S .

    - name: Build library
      timeout-minutes: 2
      run: cmake --build build/

    - name: Check if library exists
      run: if [ ! -e "${{ env.LIBRARY }}" ]; then exit 1; fi
